version: '3'

services: 
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_PASS=0000
    ports:
      - 27017:27017
  imageloader:
    image: mspandrade/imageloader
    depends_on:
      - mongodb
    ports:
      - 80:8080
    environment:
      - spring_data_mongodb_uri=mongodb://mongodb:27017/imageloader
      - spring_data_mongodb_password=0000
    links:
      - mongodb